spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: expert

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}